name: dye_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  image: ^3.2.0
  color: ^3.0.0
  args: ^2.3.1
  console_bars: ^1.0.5
