name: Build

on:
  - push
  - pull_request

jobs: 
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: cedx/setup-dart@v3
        with:
          release-channel: dev
      - name: Build
        run: |
          dart pub get
          dart compile exe bin/dye.dart
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: dye-${{ matrix.os }}.zip
          path: 'bin'
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          name: dye-${{ matrix.os }}.zip
          path: dye-${{ matrix.os }}.zip
