name: Build

on:
  workflow_dispatch: 
  release: 
    types: [released]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: iffy/install-nim@v4
        with:
          version: binary:stable
      - name: Build
        run: |
          nimble install -d -y
          nimble build -d:release --deepcopy:on
      - uses: thedoctor0/zip-release@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          type: 'zip'
          filename: dye-linux.zip
          path: dye
      - uses: thedoctor0/zip-release@main
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          type: 'zip'
          filename: dye-windows.zip
          path: dye.exe

      - name: Release
        uses: ananoufo/action-upload-artifacts-and-release-assets@main  
        with:
          path: "dye-*.zip"
          github-token: ${{ secrets.github_token }}
          upload-release-files: true
